# Generated by Django 5.0.2 on 2024-07-15 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myschool", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="fiest_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="fiest_name",
            new_name="first_name",
        ),
    ]
