# Generated by Django 5.0.2 on 2024-07-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myschool", "0003_student_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
