# Generated by Django 5.0.7 on 2024-07-19 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myschool", "0004_teacher_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="teacher_class",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
