# Generated by Django 5.0.7 on 2024-07-19 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myschool", "0005_remove_teacher_teacher_class_delete_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("password", models.TextField()),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "student_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_student",
                        to="myschool.classes",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("password", models.TextField()),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "teacher_class",
                    models.ManyToManyField(
                        db_index=True,
                        related_name="class_teacher",
                        to="myschool.classes",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
