# Generated by Django 5.0.2 on 2024-07-20 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myschool", "0006_student_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETE", "Complete"),
                            ("NOT_COMPLETE", "Not Complete"),
                            ("PENDING", "Pending"),
                            ("PROGRESS", "In Progress"),
                        ],
                        default="P",
                        max_length=12,
                    ),
                ),
                (
                    "class_assigned",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="class_assigned",
                        to="myschool.classes",
                    ),
                ),
                (
                    "student_assigned",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assigned",
                        to="myschool.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
