# Generated by Django 5.0.2 on 2024-07-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myschool", "0009_task_teacher_assigned_alter_task_class_assigned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="class_assigned",
        ),
        migrations.RemoveField(
            model_name="task",
            name="teacher_assigned",
        ),
        migrations.AddField(
            model_name="task",
            name="class_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_assigned",
                to="myschool.classes",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="teacher_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assigned",
                to="myschool.teacher",
            ),
        ),
    ]
