# Generated by Django 5.0.2 on 2024-08-05 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myschool", "0013_classtask_getmarks_task_marks"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("addresses", models.TextField()),
                (
                    "students",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="StudentAddress",
                        to="myschool.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
